/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ArticlePanel: typeof import('./src/components/ArticlePanel.vue')['default']
    ControlPanel: typeof import('./src/components/ControlPanel.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    HistoryPanel: typeof import('./src/components/HistoryPanel.vue')['default']
    InputPanel: typeof import('./src/components/InputPanel.vue')['default']
    StatsPanel: typeof import('./src/components/StatsPanel.vue')['default']
  }
}
